### ISSUE TITLE
SetValueRaw not represented in DotNet Wrapper 

### ISSUE THREAD

**Issue by dotMorten** [OpenZWave/openzwave-dotnet-uwp#2]
From https://github.com/OpenZWave/open-zwave/issues/790

`GetValueAsRaw`: http://openzwave.com/dev/classOpenZWave_1_1Manager.html#ab66a00a45f2c2593ad4a22da5024167c
`SetValue(byte[])`: http://openzwave.com/dev/classOpenZWave_1_1Manager.html#a8668c10e99f539b1affd2c72edee9695
`ValueRaw` class:  http://openzwave.com/dev/classOpenZWave_1_1ValueRaw.html

**Comment by dotMorten** [comment]
@dechutes I can provide the implementation if you're willing to give it a test-run to ensure it works.

**Comment by dechutes** [comment]
Absolutely!  Thanks for the help

**Comment by dechutes** [comment]
I'm probably just missing it, but what do I call to do the set in .net?

**Comment by dotMorten** [comment]
Added
