### ISSUE TITLE
NodeNew Event not raised

### ISSUE THREAD

**Issue by markolb81** [OpenZWave/openzwave-dotnet-uwp#21]
Hi, I noticed that the NodeNew Notification does not occur, when adding new nodes via Inclusion Mode to the ZWave Network.

As far as I understood, the event is a virtual event, thrown by OpenZWave as soon as it detects a node which is not in the ozw-config-xml file. 

My observation in detail:
- If you  delete the configuration while a node is still paired to the network, restart the application, then "NodeNew" occurs (for both the controller and other nodes)
- If you remove and re-connect a device to the network while the application is running, the NodeNew Event does not occur.
- If you start the application, let it initialize existing nodes and then add a new node to the network, the NodeNew event does not occur.

Is it possible that the configuration is being updated too early, so that the check if the device already exists will always deliver "already exists"?

Unfortunately, I'm not good at c++ programming, otherwise I'd resolve it myself. I believe the problem is in Driver.cpp in "HandleSerialAPIGetInitDataResponse"

**Comment by dotMorten** [comment]
Since this library is just wrapping the native OpenZWave library, and you confirmed the event can actually fire (confirming the wrapper works), this is probably better to ask in the [OpenZWave repo](https://github.com/OpenZWave/open-zwave/issues).
