### ISSUE TITLE
1.6 Update - ValueID index param changed to uint16_t (openzwave-dotnet-uwp)

### ISSUE THREAD

**Issue by Fishwaldo** [OpenZWave/openzwave-dotnet-uwp#24]
Per the OZW 1.6 Release Notes, [the index of all ValueID's has changed from a unt8_t to a uint_16_t](https://github.com/OpenZWave/open-zwave/wiki/OpenZWave-1.6-Release-Notes#valueid-index-range) 

Need to ensure no changes are required

**Comment by dotMorten** [comment]
Already done. https://github.com/OpenZWave/openzwave-dotnet-uwp/commit/acf9c61f8d86794dfd07ff96b3881a966b07a9f1
