### ISSUE TITLE
Alive

### ISSUE THREAD

**Issue by campaignium** [OpenZWave/openzwave-dotnet-uwp#43]
Is this project still alive? Would be so awesome if we could get an update that syncs this project up with the main OpenZWave project

**Comment by yesyesuk** [comment]
Yes, me too. I'd love to have the central scene support in this library.
I read in another post here that there is some issue with DNS, which I didn't really understand.

**Comment by ftballguy45** [comment]
Same here - I did not understand the DNS issue. Would love to have this library updated

**Comment by dotMorten** [comment]
It's in sync with master of open-zwave (albeit pending a PR over there to make things compile)

**Comment by ftballguy45** [comment]
I downloaded the latest and it doesn't compile. Are there any steps that need to be performed so that this can compile?

**Comment by dotMorten** [comment]
@ftballguy45 for the sub module did you switch to the pending PR?
