### ISSUE TITLE
Update nuget package

### ISSUE THREAD

**Issue by dotMorten** [OpenZWave/openzwave-dotnet-uwp#5]
Nuget package needs to be updated to move in under the OpenZWave org.
The refactoring does contain some namespace changes and clean up and removed deprecated members from the older .NET version, so .NET and UWP can share code, and also simplify code.

While these changes are major, they are breaking, and as such gives us two options:

1. Breaking changes must be done in a major version (according to SemVer). Move to 2.0.0-beta1
2. Create an entirely new package name.

It's not clear who owns the "OpenZwave" package on nuget. @Fishwaldo? If this is an unofficial package, it only leaves us option 2.

**Comment by Fishwaldo** [comment]
@bufferUnderrun Can you transfer the Nuget Packet (or grant access to dotMorten) so he can update?

**Comment by Fishwaldo** [comment]
if all else fails - you can try to transfer ownership (last paragraph) here: https://docs.microsoft.com/en-us/nuget/create-packages/publish-a-package

**Comment by bufferUnderrun** [comment]
@Fishwaldo for sure, i can transfert the ownership of the nuget package to dotMorten. The nuget package i made was only to help users to play with openzwavedotnet easily.

@dotMorten can you confirm that your username in nuget is also "dotMorten" ?

**Comment by dotMorten** [comment]
@bufferunderrun awesome. My username on nuget is `mnielsen`

**Comment by bufferUnderrun** [comment]
@dotMorten task done, you will receive approval notification

**Comment by dotMorten** [comment]
Awesome. I'm running through some final API review and ensure UWP and .NET is consistent and following proper naming guidelines all the way through. Once complete, I'll push out a 2.0.0-beta package. Sounds good?

**Comment by dotMorten** [comment]
Done
