### ISSUE TITLE
Can't find log files on Windows IoT

### ISSUE THREAD

**Issue by fs99erab** [OpenZWave/openzwave-dotnet-uwp#9]
I am running this on a raspberry pie and Windows IoT. Quite new to all of it.
When looking at the code, it looks like the log files should be saved in the app-folder, but can't seem to find the log file there.
I am searching with the file explorer in Windows IoT web interface.
Any thoughts?

**Comment by dotMorten** [comment]
They are not in the app folder (that's read only), but in the ApplicationData.LocalFolder. 
https://docs.microsoft.com/en-us/uwp/api/windows.storage.applicationdata#properties_

**Comment by dotMorten** [comment]
Also here's that default folder for uwp set https://github.com/OpenZWave/openzwave-dotnet-uwp/blob/master/src/OpenZWave/ZWOptions.cpp#L54

**Comment by fs99erab** [comment]
You're right. Found it when viewed through SMB. Thanks.
Thank you for a wrapper. It's awesome!

**Comment by dotMorten** [comment]
Thank you. @donald-hanson deserves most of the credit as he did all the hard initial work. I just added a little finishing polish 😀
